dist: bionic
sudo: required

env:
  global:
    - DPL_DEBUG=true

services:
  - docker

before_install:
  - gem install bundler
  - bundle config set force_ruby_platform true
  - docker build -t kzs/docker-react -f Dockerfile.dev .

script:
  - docker run kzs/docker-react npm run test -- --coverage

deploy:
  provider: script
  script: |
    gem install dpl
    dpl --provider=elasticbeanstalk \
        --access_key_id="${AWS_ACCESS_KEY}" \
        --secret_access_key="${AWS_SECRET_KEY}" \
        --app="zsolt-docker-ci" \
        --env="Zsolt-docker-ci-env" \
        --region="eu-north-1" \
        --bucket="elasticbeanstalk-eu-north-1-746669227871" \
        --bucket_path="zsolt-docker-ci" \
        --debug
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY